<div class="content-wrapper">
    <div class="content_header">
        <h3>Create Invoice <span class="ims_tooltip" data-toggle="tooltip" data-placement="right" title="Request Invoices have three sections Invoice Details, Client Details and PO Details. For Requesting new Invoice enter valid data in Invoice Details, Client Details and PO Details. New Invoice Requested to Account department."><i class="fa fa-info-circle"></i></span></h3>
    </div>
    <div class="inner_bg content_box">
		<div class="row">
        <?php if($this->session->flashdata('error') != '') { ?>
            <div class="alert alert-danger" style="margin-top:18px;">
                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                <?php echo $this->session->flashdata('error'); ?>
            </div>
        <?php } ?>
        <?php if($this->session->flashdata('success') != '') { ?>
            <div class="alert alert-success" style="margin-top:18px;">
                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                <?php echo $this->session->flashdata('success'); ?>
            </div>
        <?php } ?>
		</div>
        <form action="" method="post" id="create-invoice" name="create-invoice" enctype="multipart/form-data">
            <div class="row">
                <div class="col-sm-12">
                    <div class="">
						
                        <div class="box-form">
							<div class="row">
								<div class="col-sm-6">
									<h3 class="form-box-title">Invoice Details <span class="ims_tooltip" data-toggle="tooltip" data-placement="top" title="By default 'Localization' category selected, If Invoice already generated by other sources then do checked check box else unchecked so that account person will generate the Invoice. Enter Project Name and select Sales Person & Manager Name from list."><i class="fa fa-info-circle"></i></span></h3>
								</div>
								<div class="col-sm-6 text-right">
									<div class="inv_generate">
										<div class="col-sm-12 invoiceGenerated"  style="display:none; ">
											<div class="form-group">
												<div class="checkbox m0">
													<input type="checkbox" id="invoice" value="Invoice Already Generated" name="invoice" />
													<label for="invoice">Invoice Already Generated</label>
												</div>
											</div>
										</div><!--col-sm-3-->
									</div>
								</div>
							</div>
                            
                            <div class="theme-form">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <div class="form-group">
											<label class="ims_form_label">Select Category*</label>
                                            <select class="ims_form_control" name="category_id" id="category_id">
                                                <option value="">Select category*</option>
                                                <?php foreach($categories as $rows) { ?>
                                                    <option value="<?php echo $rows->id?>"><?php echo ucfirst($rows->category_name)?></option>
                                                <?php } ?>
                                             </select>
                                        </div>
                                    </div><!--col-sm-3-->

                                    <div class="col-sm-3 subcategory"  style="display:none; ">
                                        <div class="form-group">
											<label class="ims_form_label">Invoice Subcategory*</label>
                                            <select class="ims_form_control" name="subcategory_id" id="subcategory_id">
                                                <option value="">Invoice subcategory*</option>
                                                <?php foreach($subcategories as $rows) { ?>
                                                    <option value="<?php echo $rows->id?>"><?php echo ucfirst($rows->category_name)?></option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                    </div><!--col-sm-3-->

                                    <div class="col-sm-3">
                                        <div class="form-group">
											<label class="ims_form_label">Campaign Name*</label>
                                            <input maxlength="100" type="text" class="ims_form_control" name="comp_name" id="comp_name" placeholder="Campaign name*">
                                            <select class="ims_form_control" name="order_id" id="order_id" style="display:none; ">
                                                <option value="">Project name*</option>
                                            </select>
                                        </div>
                                    </div><!--col-sm-3-->

                                    <div class="col-sm-3 suborder" style="display:none; ">
                                        <div class="form-group">
											<label class="ims_form_label">Select Order</label>
                                            <select class="ims_form_control" name="suborder_id" id="suborder_id">
                                                <option value="">Select order</option>
                                            </select>
                                        </div>
                                    </div><!--col-sm-3-->

                                    <div class="col-sm-3">
                                        <div class="form-group">
											<label class="ims_form_label">Webdunia Sales Person*</label>
                                            <select class="ims_form_control" name="sales_person" id="sales_person">
                                                <option value="">Webdunia Sales person*</option>
                                                <?php foreach($wdsalesperson as $rows) { ?>
                                                    <option <?php echo ( $currentUserId == $rows->id)? "selected=selected" : ""; ?> value="<?php echo $rows->id?>"><?php echo ucfirst($rows->name)?></option>
                                                <?php } ?>
                                             </select>
                                        </div>
                                    </div><!--col-sm-3-->
                                    <div class="col-sm-3">
                                        <div class="form-group">
											<label class="ims_form_label">Webdunia Manager*</label>
                                            <select class="ims_form_control" name="manager_person" id="manager_person">
                                                <option value="">Webdunia Manager*</option>
                                                <?php foreach($wdmanager as $rows) { ?>
                                                    <option value="<?php echo $rows->id?>"><?php echo ucfirst($rows->name)?></option>
                                                <?php } ?>
                                             </select>
                                        </div>
                                    </div><!--col-sm-3-->
                                </div><!--row-->
                            </div><!--theme-form-->
                        </div><!--box-form-->

                        <div class="row">
                            <div class="col-sm-12" id="invoicebox" style="display: none">
                            <div class="row-invsch">
                            <div class="box-form schedule" id="schedule">
                                <h3 class="form-box-title">Invoice Schedule Details <span class="ims_tooltip" data-toggle="tooltip" data-placement="top" title="Select Client Name from list for that you want to raise invoice, by press 'Add/Edit Client' Add new client details and edit existing client details. Select Sales & Account persons from list and after selection his Postal Address, Contact Number & Email Id showing."><i class="fa fa-info-circle"></i></span></h3>

                                <div class="rowtheme-form invoice_schedule_box" id="invoiceScheduleBox">
                                    <div class="row" id="invoice_schedule_row_1">
                                        <div class="col-sm-3">
											<div class="checkbox bef_check">
												<input type="checkbox" value="" name="invoice_schedule_id[]" onclick="setInvoiceAmount();">
												<label for="inlineRadio3"></label>
											</div>
                                            <div class="form-group bef_check">
                                                <input type="text" name="invoice_startdate[]" id="invoice_startdate_1" class="invoice_schedule_date ims_form_control date_icon sel_date"  readonly="readonly"  placeholder="Start date" />
                                            </div>
                                        </div>
                                        <div class="col-sm-3">
                                            <div class="form-group">
                                                <input maxlength="15" type="text" name="invoice_amount[]" id="invoice_amount_1" class="ims_form_control amount"  readonly="readonly"placeholder="Amount" />
                                            </div>
                                        </div>
                                        <div class="col-sm-3">
                                            <div class="form-group">
                                                <input maxlength="150" type="text" name="invoice_comment[]" id="invoice_comment_1" class="ims_form_control"  readonly="readonly" placeholder="Comment" />
                                            </div>
                                        </div>
                                        <div class="col-sm-3">
                                            <div class="form-group">
                                                <div class="radio radio-inline">
                                                    <input type="radio" id="invoice_status_c_1" value="C" disabled='disabled' name="invoice_status_1">
                                                    <label for="invoice_status_c_1"> Confirmed</label>
                                                </div>
                                                <div class="radio radio-inline">
                                                    <input type="radio" id="invoice_status_t_1" value="T" disabled='disabled' name="invoice_status_1">
                                                    <label for="invoice_status_t_1"> Tentative </label>
                                                </div>
                                            </div>
                                        </div>
                                </div>

                                <!--row-->
                                <div>
                                    <input type="hidden" name="invoice_schedules" id="invoice_schedules" value="1">
                                </div>
                                    <div id="totalamount"><strong>Total Invoice Amount : <span id="totalInvoiceAmount"></span></strong></div>

                                </div><!--theme-form-->
                            </div>

                            </div>
                            </div>

                            </div>



                        <div class="row">
                            <div class="col-sm-12" id="tnmbox" style="display: none">
                                <div class="row">
                                    <div class="box-form">
                            <h3 class="form-box-title">TNM Details <span class="ims_tooltip" data-toggle="tooltip" data-placement="top" title="Select Client Name from list for that you want to raise invoice, by press 'Add/Edit Client' Add new client details and edit existing client details. Select Sales & Account persons from list and after selection his Postal Address, Contact Number & Email Id showing."><i class="fa fa-info-circle"></i></span></h3>
                                <div class="rowtheme-form tnm_schedule_box" id="tnmScheduleBox">
                                    <div class="row" id="tnm_schedule_row_1">
                                        <div class="col-sm-3">
                                            <div class="form-group">
												<label class="ims_form_label">Consumption</label>
                                    <input maxlength="10" name="initial_hours" type="text" class="ims_form_control" id="initial_hours" placeholder="Consumption"  maxlength="10" readonly/>
                                   </div>
                                            </div>
                                        <div class="col-sm-3">
                                            <div class="form-group">
												<label class="ims_form_label">Unit</label>
                                    <select id="effort_unit" name="effort_unit" class="ims_form_control" readonly="readonly">
                                        <option value="-1">Unit</option>
                                        <option value="H">Hours</option>
                                        <option value="D">PD's</option></select>
                                </div>
                                            </div>
                                        <div class="col-sm-3">
                                            <div class="form-group">
												<label class="ims_form_label">Unit rate</label>
                                <input maxlength="10" name="hourly_rate" type="text" class="ims_form_control" id="rate" placeholder="Unit rate"  readonly/>
                                                </div>
                                            </div>

                                        <div class="col-sm-3">
                                            <div class="form-group">
												<label class="ims_form_label">Currency</label>
                                    <select name="hour_curncy" id="hourCurncy" class="ims_form_control" readonly="readonly">
                                        <option value="">Currency</option>
                                        <?php foreach($currencyname as $rows) { ?>
                                            <option value="<?php echo $rows->currency_id?>"><?php echo ucfirst($rows->currency_name)?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                                </div>
                                        </div>
                                    </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="box-form client">
                            <h3 class="form-box-title">Client's Account's Details <span class="ims_tooltip" data-toggle="tooltip" data-placement="top" title="Select Client Name from list for that you want to raise invoice, by press 'Add/Edit Client' Add new client details and edit existing client details. Select Sales & Account persons from list and after selection his Postal Address, Contact Number & Email Id showing."><i class="fa fa-info-circle"></i></span></h3>
                            <div class="theme-form">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group inline_info">
											<label class="ims_form_label">Select Client name*</label>
                                            <select class="ims_form_control" name="client_name" id="client_name">
                                                <option value="">Select client name*</option>
                                             </select>

                                                <a href="javascript:void(0)" onclick="addMoreClient();" style="display: none" id="add_more" class="add_more_btn pull-right mdl-js-button mdl-js-ripple-effect ripple-white"><img src="<?php echo base_url() ?>assets/images/plus_bordered.svg"  /></a>

                                        </div>
                                    </div><!--col-sm-6-->
                                    <div class="col-sm-6">
                                        <div class="form-group">
											<label class="ims_form_label">Postal Address*</label>
                                            <textarea maxlength="250" class="ims_form_control" rows="2" name="postal_address" placeholder="Postal address*" readonly="readonly" id="postal_address"></textarea>
                                        </div>
                                    </div><!--col-sm-6-->
                                    <div class="col-sm-12">
                                        <h5 class="form-box-subtitle">Manager's Details</h5>
                                        <div class="row">
                                            <div class="col-sm-4">
                                                <div class="form-group">
													<label class="ims_form_label">Name</label>
                                                    <select class="ims_form_control" name="manager_name" id="manager_name">
                                                        <option value="">Name</option>
                                                     </select>
                                                </div>
                                            </div><!--col-sm-4-->
                                            <div class="col-sm-4">
                                                <div class="form-group">
													<label class="ims_form_label">Contact Number</label>
                                                    <input maxlength="50" type="text" class="ims_form_control" name="contact_number" id="contact_number" readonly="readonly" placeholder="Contact number">
                                                </div>
                                            </div><!--col-sm-4-->
                                            <div class="col-sm-4">
                                                <div class="form-group">
													<label class="ims_form_label">Email</label>
                                                    <input maxlength="150" type="text" class="ims_form_control" name="email_id" id="email_id" readonly="readonly" placeholder="Email">
                                                </div>
                                            </div><!--col-sm-4-->
                                        </div><!--row-->
                                    </div><!--col-sm-12-->
                                    <div class="col-sm-12">
                                        <h5 class="form-box-subtitle">Client's Accounts Details</h5>
                                        <div class="row">
                                            <div class="col-sm-4">
                                                <div class="form-group">
													<label class="ims_form_label">Name</label>
                                                    <select class="ims_form_control" name="acc_person" id="acc_person">
                                                        <option value="">Name</option>
                                                     </select>
                                                </div>
                                            </div><!--col-sm-4-->
                                            <div class="col-sm-4">
                                                <div class="form-group">
													<label class="ims_form_label">Contact Number</label>
                                                    <input maxlength="50" type="text" class="ims_form_control" name="contact_number1" id="contact_number1" readonly='readonly' placeholder="Contact number">
                                                </div>
                                            </div><!--col-sm-4-->
                                            <div class="col-sm-4">
                                                <div class="form-group">
													<label class="ims_form_label">Email</label>
                                                    <input maxlength="150" type="text" class="ims_form_control" name="email_id1" id="email_id1" readonly="readonly" placeholder="Email">
                                                </div>
                                            </div><!--col-sm-4-->
                                        </div><!--row-->
                                    </div><!--col-sm-6-->
                                </div><!--row-->
                            </div><!--theme-form-->
                        </div><!--box-form-->
                        <div class="box-form">
							<div class="row">
								<div class="col-sm-6">
									<h3 class="form-box-title"><span class="po_heading">PO Details</span> <span class="ims_tooltip" data-toggle="tooltip" data-placement="top" title="The description entered here will be a part of invoice."><i class="fa fa-info-circle"></i></span></h3>
								</div>
								<div class="col-sm-6 text-right">
									<div class="nopo text-right"  style="display:none;" >
                                        <div class="form-group">
											<label class="ims_form_label"></label>
                                            <div class="checkbox m0">
                                                <input type="checkbox" id="no_po" value="option1" name="no_po" onclick="setPoDetails();" />
                                                <label for="no_po"> No PO</label>
                                            </div>
                                        </div>
                                    </div>
								</div>
							</div>
                            
                           
                                 <div class="theme-form">
                                 <div class="row">
                                    <div class="col-sm-3">
                                        <div class="form-group">
											<label class="ims_form_label">PO/RO Number*</label>
                                            <input maxlength="100" type="text" class="ims_form_control" name="po_ro_number" id="po_ro_number" placeholder="PO/RO number*">
                                        </div>
                                    </div><!--col-sm-3-->
									 <div class="col-sm-3">
                                        <div class="form-group">
											<label class="ims_form_label">PO/RO Date*</label>
                                            <input type="text" name="po_ro_date" id="po_ro_date" class="ims_form_control date_icon sel_date" readonly  placeholder="PO/RO date*"/>
                                        </div>
                                    </div><!--col-sm-3-->


                                    <div class="col-sm-6">
                                        <div class="form-group podetail">
											<label class="ims_form_label">PO Details*</label>
                                            <textarea maxlength="150" class="ims_form_control" rows="3" name="po_detail" placeholder="PO details*" id="po_detail"></textarea>
                                        </div>
                                    </div><!--col-sm-3-->
									 <div class="col-sm-3" style="display:none;"><!--NO NEED THIS ANY MORE-03-MAY-18 -->
									 	<div class="status"  style="display:none;" >
											<div class="radio">
												<input type="radio" id="without" value="NO" name="wpc_status" checked="checked">
												<label for="without"> Without WPC</label>
											</div>
											<div class="radio">
												<input type="radio" id="with" value="YES" name="wpc_status" checked="">
												<label for="with"> With WPC </label>
											</div>
											   </div>
									 </div>
                                    


									 <div class="clearfix"></div>
                                    <div class="col-sm-6">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <div class="form-group">
													<label class="ims_form_label">Net Invoice Amount*</label>
                                                    <input maxlength="10" type="text" class="ims_form_control" name="inv_amount" id="inv_amount" placeholder="Net invoice amount*">
                                                </div>
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="form-group">
													<label class="ims_form_label">Currency*</label>
                                                    <select class="ims_form_control" name="currency" id="currency">
                                                        <option value="">Currency*</option>
                                                        <?php foreach($currencyname as $rows) { ?>
                                                            <option value="<?php echo $rows->currency_id?>"><?php echo ucfirst($rows->currency_name)?></option>
                                                        <?php } ?>
                                                     </select>
                                                </div>
                                            </div>


                                        </div><!--row-->
                                    </div><!--col-sm-7-->
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            <label class="ims_form_label">Client Agreements</label>
											<div class="ims_multiselect">
                                              <span id="noAttachment"></span>
												
                                             <select title="Client agreements" class=" selectpicker" id="client_agreement" name="client_agreement[]"  multiple="multiple" >
                                                    <?php foreach($agreementname as $rows) { ?>
                                                        <option value="<?php echo $rows->agreement_id?>"><?php echo ucfirst($rows->agreement_name)?></option>
                                                    <?php } ?>

                                                </select>

                                            </div>
                                            <label id="client_agreement-error" class="error" for="client_agreement" style="display: none;"></label>
                                        </div>
                                    </div><!--col-sm-4-->
                                    <div class="col-sm-3">
                                        <div class="form-group">
											<label class="ims_form_label">Payment term*</label>
                                            <select class="ims_form_control" name="pay_term" id="pay_term">
                                                <option value="">Payment term*</option>
                                                <?php foreach($paymentterm as $rows) { ?>
                                                    <option value="<?php echo $rows->id?>"><?php echo ucfirst($rows->name)?></option>
                                                <?php } ?>
                                             </select>
                                        </div>

                                    </div><!--col-sm-4-->
									 <div class="clearfix"></div>
                                    <div class="col-sm-3 deliveryRequired"  style="display:none; ">
                                        <div class="form-group">
											<label class="ims_form_label">Delivery Required*</label>
                                            <input maxlength="10" type="text" class="ims_form_control" name="delivery_required" id="delivery_required" placeholder="Delivery required*">
                                        </div>
                                    </div>
                                    <div class="col-sm-3 actualDelivered"  style="display:none; ">
                                        <div class="form-group">
											<label class="ims_form_label">Actual Delivered*</label>
                                            <input maxlength="10" type="text" class="ims_form_control" name="actual_delivered" id="actual_delivered" placeholder="Actual delivered*">
                                        </div>
                                    </div>

                                    <div class="col-sm-3 units"  style="display:none; ">
                                        <div class="form-group">
											<label class="ims_form_label">Unit*</label>
                                            <select class="ims_form_control" name="units" id="units">
                                                <option value="">Unit*</option>
                                                <?php foreach($impressionunits as $rows) { ?>
                                                    <option value="<?php echo $rows->id?>"><?php echo ucfirst($rows->unit_name)?></option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                    </div>
									 
                                    
                                    
                                    <div class="col-sm-12 order_attachment_box" id="order_attachment_box_1">
                                        <div class="row">
                                        <div class="col-sm-6" id="invoice_doc_1">
                                            <div class="form-group">
												<label class="ims_form_label">Select Type</label>
                                                <select name="add_invoice_doc[]" id="invoice_doc1" class="ims_form_control attachtype">
                                                    <option value="">Select type</option>
                                                    <option value="opf">Order Processing Form</option>
                                                    <option value="ro">Release/Work Order</option>
                                                    <option value="agreement">Agreement</option>
                                                    <option value="eml">Email file</option>
                                                    <option value="client_report">Client Report</option>
                                                    <option value="wrk_smry">Work Summary</option>
                                                    <option value="others">Others</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-sm-6 attach_col attach" id="attachment_1">
                                            <div class="form-group order-attachment-group">
												<label class="ims_form_label">Name of Agreement</label>
                                                <div class="file-upload-wrapper" id="file-upload-wrapper_1">
                                                    <input type="file" name="add_agreement_name[]" id="attachment1" class="ims_form_control upload_icon custom-file-upload-hidden" placeholder="Name of Agreement" tabindex="-1" aria-invalid="false" style="position: absolute; left: -9999px;">
                                                    <input style="display: none" type="text" name="file-upload-input[]" id="file-upload-input_1" class="file-upload-input" placeholder="Attachment" readonly>
                                                    <span class="file-upload-span"></span>
                                                    <button type="button" class="file-upload-button file-upload-select" tabindex="-1">
                                                    </button>
                                                </div>
                                                <label id="file-upload-input_1-error" class="error" for="file-upload-input_1" style="display: none;"></label>
                                                <a href="javascript:void(0);" class="delete_record delete_attachment" style="display:none"><img src="<?php echo base_url();?>assets/images/delete_icon.svg" /></a>
												<a href="javascript:void(0)" onclick="addMoreAttachment()"  class="add_more_btn mdl-js-button mdl-js-ripple-effect ripple-white add"><img src="<?php echo base_url() ?>assets/images/plus_bordered.svg"  /></a>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <div class="form-group add_more_attach_inv">

                                            
                                        </div>
                                    </div>

                                    <div class="clearfix"></div>

                                    <div class="col-sm-12">
                                        <div class="form-group">
											<label class="ims_form_label">Remark</label>
                                            <textarea maxlength="150" class="ims_form_control" rows="3" name="remarks" placeholder="Remark" id="remarks"></textarea>
                                        </div>
                                    </div><!--col-sm-12-->
                                </div><!--row-->
                            </div><!--theme-form-->
                        </div><!--box-form-->
                            <div class="form-footer">
                                <input type="submit" id="submit" name="submit" value="Create Invoice" class="btn-theme btn-submit mdl-js-button mdl-js-ripple-effect ripple-white" >
                                <input id="resetInvoice" name="reset" type="reset" class="btn-theme btn-reset ml10 mdl-js-button mdl-js-ripple-effect ripple-white" value="Reset">
                            </div>
                    </div><!--row-->
                </div><!--col-sm-12-->
            </div><!--row-->
        </form>
    </div><!--inner_bg-->
</div><!--content-wrapper-->
<!-- View Modal-->
<div id="addClientModal" class="modal">
    <div class="modal-dialog modal-lg zoomIn animated">
        <div class="modal-content bg-white">
            <div class="modal-header ims_modal_header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Add Client</h4>
            </div>
            <div class="modal-body view-details1 custom_scroll bg-white pt-0 pb-0">

            </div><!--modal-body-->
        </div>
    </div>
</div>
<script src="<?php echo base_url();?>assets/js/create-invoice.js"></script>
<script>
    function addMoreClient() {
        $('#addClientModal').modal('show');
    }

    $("#addClientModal").on("show.bs.modal", function(e) {
        var modal = $(this);
        modal.find('.view-details1').html("");
        var id = $('#category_id').val();
        var viewUrl = BASEURL + "clients/add-newclient";
        $.ajax({
            type: "POST",
            url: viewUrl,
            dataType:'json',
            data:{category_id:id,type:'invoice'},
            cache: false,
            success: function (data) {
                modal.find('.view-details1').html(data.viewHtml);
                $(".custom_client_scroll").mCustomScrollbar();
            },
            error: function(err) {
                console.log(err);
            }
        });
    });
</script>